#!/usr/bin/python3
from __future__ import division, print_function
import argparse
import os
import sys


parser = argparse.ArgumentParser(
    description='Check that the directories given are empty')
parser.add_argument(
    'directories', metavar='dir', nargs='+', type=str,
    help='directory to be checked')
args = parser.parse_args()


for directory in args.directories:
    listdir = os.listdir(directory)
    if len(listdir) != 0:
        print('WARNING: Directory {} is not empty ({} entries)'
              .format(directory, len(listdir)))
        sys.exit(1)

print('OK: All given directories are empty')
sys.exit(0)
